# Generated by Django 4.1.2 on 2022-10-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='сategory',
            new_name='category',
        ),
    ]
