# Generated by Django 4.1.2 on 2022-11-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='catalog_images/defoult_category.png', upload_to='catalog_images', verbose_name='Титульная изображения'),
        ),
    ]
