# Generated by Django 4.1.2 on 2022-10-17 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('shop', '0003_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Создана'), ('canceled', 'Отменена'), ('completed', 'Завершена')], default='created', max_length=30, verbose_name='Статус')),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userbot')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(verbose_name='Общая сумма заказа')),
                ('payment_system', models.CharField(max_length=250, verbose_name='Платежная система')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('canceled', 'Отменен')], default='waiting', max_length=50, verbose_name='Статус')),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userbot')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectedProductOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('added', 'Новый'), ('deleted', 'Удален')], default='added', max_length=30, verbose_name='Статус')),
                ('actual_price', models.IntegerField(verbose_name='Актуальная цена')),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Товар выделенный в заказ',
                'verbose_name_plural': 'Товары выделенные в заказ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectedProductBasket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('added', 'Новый'), ('deleted', 'Удален')], default='added', max_length=30, verbose_name='Статус')),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Товар выделенный в корзину',
                'verbose_name_plural': 'Товары выделенные в корзину',
                'ordering': ['created_at'],
            },
        ),
    ]
