# Generated by Django 4.1.2 on 2022-10-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(choices=[('mbank', 'M-Bank'), ('optima', 'Optima bank'), ('demir', 'Демир банк')], default='mbank', max_length=50, verbose_name='Платежная система'),
        ),
    ]
