# Generated by Django 4.1.2 on 2022-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0003_alter_order_payment_system_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
